### ISSUE TITLE
CV: .filetags may contain mandatory options

### ISSUE THREAD

**Issue by novoid** [novoid/filetags#17]
Controlled vocabulary files may contain a list of command line options that are mandatory.

Example: `#options --recursive --filebrowser thunar` always uses functions recursive and opens results in thunar (instead of a different default browser).

FIXXME:

- What about contradicting CLI options?
  - example 1: `--filebrowser thunar` in .filetags and `--filebrowser geeqie` in command line?
  - example 2: `--tagtrees-depth 3` in .filetags and user just wants to tag a file (which does not allow/need tagtrees at all and results in an error)

**Comment by tuxlifan** [comment]
Yes, please!

ad ex.1: CLI options should win through higher specificity (with possibly a warning being displayed).

ad ex.2: `filetags --tagtrees-depth 3 foo` seems to work without problem to just add a tag here? In case of conflicting modes I think that again CLI input should win as it signifies the current intent of the user.

jm2c

**Comment by novoid** [comment]
Short remark on ex.2: I plan to separate filetags from tagtrees using a separate Python script within the same repository. Tagtrees has been a small feature but got bigger and bigger.

**Comment by novoid** [comment]
I'm going to close this because #16 is a much better solution although it doesn't allow "overriding" this config file in a .filetags file which is located in a deeper level within the file system hierarchy.
