### ISSUE TITLE
filetags command in CLI not found

### ISSUE THREAD

**Issue by anthrolisp** [novoid/filetags#23]
On Ubuntu 18.04
Install via pip install:
pip install filetags
Collecting filetags
Collecting pyreadline (from filetags)
Collecting clint (from filetags)
Collecting colorama (from filetags)
  Using cached https://files.pythonhosted.org/packages/4f/a6/728666f39bfff1719fc94c481890b2106837da9318031f71a8424b662e12/colorama-0.4.1-py2.py3-none-any.whl
Collecting args (from clint->filetags)
Installing collected packages: pyreadline, args, clint, colorama, filetags
Successfully installed args-0.1.0 clint-0.5.1 colorama-0.4.1 filetags-2018.1.29.3 pyreadline-2.1

At the command line: 
$ filetags
filetags: command not found

Thank you in advance!

**Comment by novoid** [comment]
Hi!
Version 2018.08.02.1 should be the latest one. My `setup.py` shows the corresponding snippet to create the command:
```
  [...]
    entry_points={  
        'console_scripts': [
            'filetags=filetags:main'
  [...]
```

Therefore, I'm puzzled why you don't get the command exposed.

**Comment by novoid** [comment]
What filetags version are you using? Check with `filetags --version`

If I don't hear back from you within the next weeks, I'll assume you could resolve the issue and close this bug.
