### ISSUE TITLE
couldn't find python module readline in ubuntu

### ISSUE THREAD

**Issue by muralikodali** [novoid/filetags#24]
installed filetags six months back. worked flawlessly. after recent update of python packages, filetags complaining error of " couldn't find python module readline" .

An image file is attached to show the error message.
I have even tried to install in virualenv with pyenv. complaining the same error.

![20190403T1049-crop](https://user-images.githubusercontent.com/11482766/55454925-41c59500-55ff-11e9-9b84-fb518978e39d.jpg)

**Comment by novoid** [comment]
On my Debian stable, I do have the package `readline-common` installed. Can you install this one via `sudo apt update && sudo apt install readline-common`?

**Comment by muralikodali** [comment]
i have already installed readline-common with version (7.0-3)

**Comment by novoid** [comment]
Can you check, if you start filetags using Python 2 or Python 3? Maybe the library is installed only for a Python version you're not using for filetags?

**Comment by muralikodali** [comment]
source of the problem is python environment variable . on my ubuntu 18.04, python defaults to python2.7

I have succesfully installed and used filetags in python3 environment with following command:

$ **python3 -m pip install filetags**

installing filetags in local python environment or virtual environment complained of
error "couldn't find python module readline".

Any way thanks for suggestion and sorry for my late reply.
