### ISSUE TITLE
tab completion doesn't work

### ISSUE THREAD

**Issue by taheriyazdi** [novoid/filetags#34]
i made a folder with some files and tested filetags.
now i removed that folder and start to tag files in a new folder but tab completion doesn't work.
is there a problem with .filetags? how can i access to it?
thanks

**Comment by taheriyazdi** [comment]
the problem was solved. 
with creating a blank file .filetags in notepad in the main folder and writing tag names in every line.
thank you for this simple but beautiful program.

**Comment by novoid** [comment]
Yes, as you have found out yourself: tag completion only works for known tags. If you start with no previous tags, you don't get tag completion.
