### ISSUE TITLE
tagging in general

### ISSUE THREAD

**Issue by kiuuik** [novoid/filetags#4]
one question about tagging in general. You have thought so much about information management so that maybe you can tell quickly whether my idea is bad. I read a lot (and have learned a lot) on your webpage and in the articles you posted online but I think you haven't written about my idea. In your software you put the tags at the end of the file names. If I don't use your software it's quite complicated to search for tags because I must use a long regular expression. I'm not sure if this is future proof because even today I'm increasingly relying on my ipad and most mobile os apps offer only a simplified UI. On my main machine I still use many scripts etc. but I think many attractive new devices won't offer the user so much freedom and I think I'll be tempted to use such devices. 
So my idea is to start all my tags will a pair of letters like qv (→ "myfilename qvtag1 qvtag2.org"). I chose a pair of letters that's very infrequent in my native language and English and tested it on my file names with find and my file contents with grep. 
Even if I only have a basic search field now I can search for tags because all my tags would start with this unique letter combination. 
Are there any drawbacks apart from the fact that it doesn't look very nice? If I wanted to use a controlled vocabulary I would have to adjust my helper script that adds or removes qv at the beginning so that I can manage my tags without seeing the prefix. But this shouldn't be too difficult.
Thanks for your time.

P.S. The way your readme.org is rendered here on github is misleading. You use a double dash to separate the tags whereas in the html version on github there is a long dash. Would it help to put `==` or `~~` around your dashes so that your line 11 looks like this: `file without time stamp in name =--= *tag2*.txt"?`

**Comment by novoid** [comment]
_What_ a comment ;-) Thanks for it!

1) How I search for files with tags

I personally use `locate` to search for files. A typical command looks like: `locate sports|grep Volleyball` and sometimes it gets as complicated as `grep sports|grep -vi mountainbi|grep bicycle` (with `sports` being one of my tags)

Another method to look for files matching a set of tags within a directory is using the filter option of filetags. If you can live with the constraint that this only searches within a single directory, this is fine.

2) Using a trigger string for tags

I don't see the difference between using `qvtag1` and `tag1` in the first place. When you are using your desktop search engine to look for `qvtag1` you can as well search for `tag1` as long as `tag1` is not contained within other tags or within a file name which is not tagged with `tag1`.

Or did you address the issue that you can not differ between searching for a tag within a file name and searching within the full text of your files (both using a desktop search engine)?

If so: that's true. But writing a Python script that searches for tag combinations recursively is rather easy for someone with basic Python knowledge. File system traversal (search performance) is also rather good IMHO.

Another option is to use a desktop search engine that allows for queries like `infilename:sports incontent:bicycle`.

3) Readme.org rendering

Thanks for the pointer, I'll fix that.

**Comment by novoid** [comment]
You should also check out the new tagtrees features I added in the recent months. I love to filter and browse through temporarily generated tagtrees.

I now close this issue. Please contact me again if you have any comment or input.
