### ISSUE TITLE
tagging in --quiet mode isn't quite quiet

### ISSUE THREAD

**Issue by nbehrnd** [novoid/filetags#43]
If filtetag's flag `-q` / `--quiet` was meant to provide a generation of tagtrees without opening Geeqie (or an other file browser), then this option seems to be defunct.

At about 42:11 mm:ss and later, the video about your presentation at GLT18 briefly shows the results of using tagtrees, especially appealing *after* running move2archive.  The bottom of the file navigator seems to list a script to rebuild this collection of links when necessary.  A valuable detail, so I wrote a bash script which is deposit into the move2archive's target folder:

```bash
#!/usr/bin/bash

filetags --tagtrees --recursive --tagtrees-depth 3 --quiet

echo "Folder /home/norwid/.filetags_tagfilter/ contains the tagstree."
```
However, despite the flag `--quiet`, Geeqie is started.

Running `filetags --tagtrees --recursive --tagtrees-depth 3 --quiet` *directly* in the CLI does yields the same observation.  It looks like this has been around for quite some time because checking out an earlier version of filtetags (2017-09-30, an earlier version of filetags to work with Python3) shares this when using flag `-q`, too.

[2022-01-23_filetags_observations.zip](https://github.com/novoid/filetags/files/7920518/2022-01-23_filetags_observations.zip)

**Comment by novoid** [comment]
Thank you for reporting. Indeed, this was never handled correctly and is fixed now.
