### ISSUE TITLE
tagtrees seems to require geeqie

### ISSUE THREAD

**Issue by ginabythebay** [novoid/filetags#44]
Trying out filetags and tagtrees for this first time, I get this:

filetags --recursive --tagtrees 
INFO     Creating tagtrees and their links. It may take a while …  (exponentially with respect to number of tags)
INFO     Number of links created in "/home/gina/.filetags_tagfilter" for the 2554 files: 2574  (tagtrees depth is 2)
Traceback (most recent call last):
  File "/home/gina/.local/bin/filetags", line 8, in <module>
    sys.exit(main())
  File "/home/gina/.local/lib/python3.10/site-packages/filetags/__init__.py", line 2575, in main
    handle_option_tagtrees()
  File "/home/gina/.local/lib/python3.10/site-packages/filetags/__init__.py", line 2444, in handle_option_tagtrees
    start_filebrowser(chosen_tagtrees_dir)
  File "/home/gina/.local/lib/python3.10/site-packages/filetags/__init__.py", line 2330, in start_filebrowser
    subprocess.call([chosen_filebrowser, directory])
  File "/usr/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'geeqie'

I installed geeqie and the error went away.  It seems like I should be able to run tagtrees without geeqie though.

**Comment by nbehrnd** [comment]
> I installed geeqie and the error went away.  It seems like I should be able to run tagtrees without geeqie though.

By default, filetags /assumes/ the presence of Geeqie as file
browser.  It is possible to override this default by the flag
`--filebrowser PATH_TO_FILEBROWSER`.  If you don't want to point to
one file browser explicitly, you set `--filebrowser none`; e.g.

```bash
filetags --recursive --tagtrees --filebrowser none
```

as outlined when running `filetags -h`.

Though, Geeqie is helpful not only for eventual tagging of images
(like .png, or .svg), but equally displays the first page of .pdf,
and symbolizes .zip archives, too.  So you can use it as an interface
to time stamp and tag the two latter file types as well.

Norwid

**Comment by novoid** [comment]
Furthermore, geeqie is one of the few tools that allow rather simple to invoke keyboard shortcuts. This way, I tag via `t`, invoke appendfilename via `a` and create TagTrees via `T`. You notice, that I don't use modifier keys here. With Thunar and other tools, you always need to find free shortcuts and use modifier keys.

With the implementation of #16, I plan to introduce defaults that may be less irritating such as "no file browser by default" which would spare you this irritating experience you have reported here.
