### ISSUE TITLE
Python 3.10+ callable change

### ISSUE THREAD

**Issue by DeutscheGabanna** [novoid/filetags#51]
Hi! Do your python scrips import a module called `Callable`? It has been moved since 3.10+ into `abc.callable` and so I'm getting errors like:
`"AttributeError: module 'collections' has no attribute 'Callable'" occurs for multiple reasons:`
when launching your scripts.

**Comment by birgens** [comment]
Hi,
I guess it may be fixed now, but for your information:

I had the same problem when using pip to install filetags on windows a few days ago. 

Based on the second answer in https://stackoverflow.com/questions/69515086/error-attributeerror-collections-has-no-attribute-callable-using-beautifu I replaced isinstance(x, collections.Callable) with isinstance(x, collections.abc.Callable) in pyreadline/py3k_compat.py. Afterwards everything seems to be working fine.

**Comment by nbehrnd** [comment]
Thank you for your complementary observation and report for the Windows
operating system.

> Based on the second answer

Note, stackoverflow/stackexchange offers more than one sort to display the
answers.  Criteria include

+ date when an answer turned in
+ date when an answer was edited
+ popularity score

which may lead to a different sequence of entries.  The indicate a specific
answer one can provide a dedicated link; this however can be a long string.
My personal preference is provide a reference similar to the pattern of

«as answer by user @author ([2023-01-28]), in the edit by @editor
([2023-01-30])»

For one, it gives the author credit where credit is due.  Sometimes, comments
(which may be erased at any time by the editors/moderators of the page)
provide additional insight which then for two -- at discretion of the original
author, or users with enough reputation score (this can, yet needn't be a
moderator, or the [original] author of the answer) -- may cause a revision of
the answer.  As one can browse in the logs of the edits, the reference then
points to the intended revision.

**Comment by novoid** [comment]
See also https://github.com/novoid/filetags/issues/54 and https://github.com/novoid/filetags/issues/54
