### ISSUE TITLE
module 'collections' has no attribute 'Callable'

### ISSUE THREAD

**Issue by dppdppd** [novoid/filetags#54]
Looks like it was moved as of 3.10?

https://stackoverflow.com/a/70641487

**Comment by dppdppd** [comment]
User error. pyreadline needs to be uninstalled and replaced with pyreadline3

**Comment by abtxu** [comment]
For anyone troubled by the =AttributeError: module 'collections' has no attribute 'Callable'= error with Python 3.10+, the following steps in the [page ](https://stackoverflow.com/questions/69515086/error-attributeerror-collections-has-no-attribute-callable-using-beautifu/70641487#70641487)works:

1. Navigate to Python310\Lib\site-packages\pyreadline in your file browser.
2. Open py3k_compat.py in an text editor.
3. Change the 8th line from which should be return isinstance(x, collections.Callable) to return isinstance(x, collections.abc.Callable).
4. Save, exit and then retry.

**Comment by novoid** [comment]
See also https://github.com/novoid/filetags/issues/51 and https://github.com/novoid/filetags/issues/49
