### ISSUE TITLE
Request: add a way to filter by tag before applying tag

### ISSUE THREAD

**Issue by shemetz** [novoid/filetags#59]
After using this tool for a while, I used `--tag-gardening` and it helpfully gave me a list that mentioned a few typos and mistakes.  However, I have no easy way of fixing those mistakes!

Specifically, in my use case, I have various files where the tag word is occasionally included in the file name itself.  This means I can't use standard shell functions to filter only for files with the wrong tag in the name.

As an example, I have a directory with many files including the following files (ttrpg battlemaps):

- Seashore.jpg
- Pirate Cove Ground Level.png
- City docks under siege.png
- Airship Docks 4.jpg

I intended to tag all of them as `dock`, but since the process was gradual over a long time, I accidentally tagged one of them differently:

- Seashore -- sea dock.jpg
- Pirate Cove Ground Level -- camp sea dock lair.png
- City docks under siege -- settlement.png
- Airship Docks 4 -- sky docks.jpg

Now I want to basically rename the tag `docks` to `dock`.  However, I have no good way of doing that based on file tags, because Filetags has no such filter option, and my shell commands for `*docks*` catch unintended files.

Currently my best solution is to rely on careful regex checks and manual work, whenever I try to fix such a mistake.

However, I think this should be an easy feature to add to this program.  One way of doing it is by specifically adding a `--rename` flag;  however, I would personally suggest making it more generic and making a `--select` flag, used like this for example: 
 `filetags --select="docks"`.  this would open the interactive tagger for all files with that specific tag.  Alternatively, this could just return an array of all those files, so re-tagging them would work by piping this command to `| filetags` again.

**Comment by novoid** [comment]
The solution for that issue I also have quite frequently is that you're 

- building a TagTrees hierarchy, 
- visit the "docks" directory within the TagTrees, 
- mark all files to be processed by filetags, 
- untag using `-docks` and add `dock`.

**Comment by shemetz** [comment]
@novoid Sadly this does not help me, and neither does using `--filter`, because my tagged files are all windows shortcut files (with the `.lnk` extension).

Apparently since they're already shortcuts, and the TagTrees/Filter functions merely create more shortcuts, editing the tags on the TagTrees/Filter files will not update the tags on my own tagged shortcut files.

**Comment by shemetz** [comment]
For now, my solution is to rely on regex:

```pwsh
$files = Get-ChildItem | Where-Object Name -match "--.* docks[. ]"
filetags $files
# then type "-docks dock"
```

**Comment by novoid** [comment]
@shemetz Oh, I see. Too bad that Microsoft is using this type of concept instead of symbolic links like all other operating systems. Hard links are no option for NTFS drives either because they would require Administrator permissions for some reason I don't understand.

I'm afraid then it's not something that will be solved by filetags (by me).

As a workaround, you could test WSL and report back if filetags within WSL is a viable solution/workaround to the problem at hand in case that WSL is providing true symbolic links instead of lnk files.
