### ISSUE TITLE
Controlled Vocabulary .filetags file not detected in Windows 11 system 

### ISSUE THREAD

**Issue by chaicurioquest** [novoid/filetags#68]
I have tried to keep .filetags in multiple locations like 
1. In the current directory where the files located.
2. Parent directory & Disk drive.
3. C:\User\Name\

filetags script could not fetch the tags either through in commandline or through batch file(from sendto-->filetags either with double TAB in GUI or any method). 

And also, I would like to change .filetags_tagfilter location from C:\User\Name\  to other location for e.g., D:\tagsearch. Is there any possibility?
Thanks. Looking forward to your reply.

**Comment by novoid** [comment]
Hi @chaicurioquest,

I don't have Windows 11 for trying to reproduce your issue.

What would be very helpful is the debug output of the script. Could you invoke `filetags -t foobar -i --dryrun --verbose *` in a path where there is a `.filetags` either directly in that directory or in any parent directory? Please post the whole output here (optionally remove any privacy-related information before).

This should give us some insight.

**Comment by chaicurioquest** [comment]
Hi @novoid ,
I have got the following message, [The .filetags.txt file is present in the directory C:\Users\Name]
C:\Users\Name>filetags -t foobar -i --dryrun --verbose *
ERROR    2024-06-22 23:34:26,034 I found option "--tag" and option "--interactive".
Please choose either tag option OR interactive mode.

**Comment by novoid** [comment]
Yes, I forgot. Drop the interactive switch and execute that:

`filetags -t foobar --dryrun --verbose *`

**Comment by chaicurioquest** [comment]
Hi @novoid,
I have made the mistake of saving file .filetags with the extension .txt.  ( ;-/@)

Due to that, It could not be located before. I have removed the extension in Notepad(Save as--> Save as type-->All files)

.filetags file was found in the directory C:\User\Name. 

DEBUG    2024-06-23 23:13:54,312 locate_and_parse_controlled_vocabulary: t**his is Windows: .filetags (non-lnk) was found**
DEBUG    2024-06-23 23:13:54,312 locate_and_parse_controlled_vocabulary: could not derive filename for controlled vocabulary
DEBUG    2024-06-23 23:13:54,312 non-interactive mode: extracting tags from argument ...
DEBUG    2024-06-23 23:13:54,312 tags found: [foobar]
DEBUG    2024-06-23 23:13:54,312 iterate over files ...

<img width="779" alt="Screenshot 2024-06-23 231739" src="https://github.com/novoid/filetags/assets/173520446/b1de278b-f7ea-4d08-97af-511ba8ec72dd">

Thanks @novoid for the PIM & filetags concept 👍. Excuse me for the trouble.

**Comment by chaicurioquest** [comment]
One more query, Can I use the following comment in  Python\Python312\Lib\site-packages\filetags\__init__.py for customized fileterd tag location(E:\.filetags_tagfilter)?
In line 72 of __init__.py file: `TAGFILTER_DIRECTORY = os.path.abspath("E:\.filetags_tagfilter")`
instead of `TAGFILTER_DIRECTORY = os.path.join(os.path.expanduser("~"), ".filetags_tagfilter").`

I could get the result in the drive location (E:\.filetags_tagfilter). However, will it cause any conflicts or issues in the future?  I used `\Python\Python312\Lib\site-packages\filetags\__init__.py --filter --recursive` for generating filtered tag output.  

Thanks

**Comment by novoid** [comment]
> Hi @novoid, I have made the mistake of saving file .filetags with the extension .txt. ( ;-/@)

Oh, error found. Perfect. 

> Thanks @novoid for the PIM & filetags concept 👍. Excuse me for the trouble.

No worries. That happens fast, espacially with Windows hiding relevant information from its users all the time.

**Comment by novoid** [comment]
Off-topic:

> One more query, Can I use the following comment in Python\Python312\Lib\site-packages\filetags__init__.py for customized filterd tag location(E:\.filetags_tagfilter)? In line 72 of **init**.py file: `TAGFILTER_DIRECTORY = os.path.abspath("E:\.filetags_tagfilter")` instead of `TAGFILTER_DIRECTORY = os.path.join(os.path.expanduser("~"), ".filetags_tagfilter").`
> 
> I could get the result in the drive location (E: \.filetags_tagfilter). However, will it cause any conflicts or issues in the future? I used `\Python\Python312\Lib\site-packages\filetags\__init__.py --filter --recursive` for generating filtered tag output.

It's open source. If you would like to use the source code and modify it to your needs, be my guest as long as you don't violate the license.

I can not comment on any future side-effect if you do modify the code as I won't remember your change and I won't refrain from modifying my code without influencing your personal modifications.

If you want to be safe, use the command line arguments only or fork the project and ignore my future enhancements (or back-port them to your code yourself).

Have a nice day!
