### ISSUE TITLE
.filetags CV-file: include other files

### ISSUE THREAD

**Issue by novoid** [novoid/filetags#7]
I want to include other .filetags files within a .filetags file like:

```
firsttag
#include ../other/subdir/additional_filetags.txt
normaltag
anothertag
```

Including other files is done in lines that must start with `#include ` followed by a relative or absolute link to a file or symbolic link or Windows shortcut file.

- [X] make sure that circular includes are detected somehow -> concept needed
  - example: `foo/.filetags` includes `bar/.filetags` which includes `baz/.filetags` which includes `foo/.filetags` **again**
  - promising approach: calculate md5sum of each CV file before loading, compare with all md5sums already loaded and stop when the md5sum is already in the list of known CV files.

**Comment by DeutscheGabanna** [comment]
This would be cool!
