### ISSUE TITLE
Using pathlib instead of os.path?

### ISSUE THREAD

**Issue by MoritzBoehme** [novoid/filetags#73]
While working on #72  I found it a bit hard to work with os.path and strings instead pathilb, which I am more used to.
I imagine using pathlib would make a lot of current code easier to read/maintain (though this could just be preference).
Would you be open to a PR changing paths to pathlib Path objects and replacing os.path functions to the respective pathlib functions?

PS: I refrained from this in my original PR, but if you also see value in this I would happily make the changes and create a PR.

**Comment by novoid** [comment]
Well, being not a good Python programmer myself, I did not even know pathlib existed.

Note to myself: 2 comparisons:
https://medium.com/@barila/choose-your-path-pythons-pathlib-vs-os-path-4de0b1e752dd (seems a bit opinionated IMHO)
https://www.machinet.net/tutorial-eng/pathlib-vs-os-path-detailed-comparison (looks more objective to me)
Both do like pathlib more.

So yeah, if you've got a PR, I'm very open to it.
